[package]
name = "buildfix-render"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

buildfix-types = { path = "../buildfix-types" }

[dev-dependencies]
pretty_assertions.workspace = true
